language: elixir
elixir:
  - 1.6
  - 1.7
  - 1.8
otp_release:
  - 19.3
  - 20.3
  - 21.2
matrix:
  exclude:
    - elixir: 1.8
      otp_release: 19.3
env:
  - PLT_DIR=$HOME/.plt
before_script:
  - mkdir -p $PLT_DIR
  - mix deps.compile
  - MIX_ENV=test mix deps.compile
  - travis_wait mix dialyzer --plt
script:
  - mix check
cache:
  directories:
    - $PLT_DIR
