sudo: false
language: elixir
elixir:
  - 1.6.6
  - 1.7.4
otp_release:
  - 19.3
  - 20.3
  - 21.1
script:
  - mix deps.compile
  - mix compile --warnings-as-errors
  - mix test --trace
  - mix dialyzer --halt-exit-status
  - mix credo
  - mix format --check-formatted
